### ISSUE TITLE
Spacing issues on CONTRIBUTORS.md

### ISSUE THREAD

**Issue by Tech-FZ** [Tech-FZ/EmuGUI#35]
While we do have a new contributor now, I forgot I have to leave a blank line between two other lines. However, as it doesn't affect functionality, this is only a very minor issue compared to some severe 32-bit MIPSel bugs on EmuGUI.

**Comment by BasDeGamer** [comment]
Can you tell me exaclty what spacing issues there are?

**Comment by Tech-FZ** [comment]
As @BasDeGamer asked, here is the exact problem:
I forgot a blank line before mentioning the new contributor. That causes CONTRIBUTORS.md to be like this:

> **EmuGUI Contributors**
> Nicolas Lucien/Tech-FZ BasDeGamer

However, it should be like this:

> **EmuGUI Contributors**
> Nicolas Lucien/Tech-FZ
> BasDeGamer

This spacing issue affects the list of contributors on both GitHub and Codeberg but can easily be fixed by adding a blank line before "BasDeGamer".

**Comment by Tech-FZ** [comment]
Don't worry, you fixed the right file, @BasDeGamer - This issue can now be closed.
