### ISSUE TITLE
CodeBerg not loading in Belarus.

### ISSUE THREAD

**Issue by Danik2343** [Tech-FZ/EmuGUI#50]
VPN Slow.
Any Alternative GitLab?

**Comment by Danik2343** [comment]
But Downloading working in Belarus.

**Comment by Tech-FZ** [comment]
I'll setup a GitLab mirror for the pre-release version soon.

**Comment by Tech-FZ** [comment]
The pre-release mirror of EmuGUI on GitLab is here: https://gitlab.com/Tech-FZ/emugui-prerelease

**Comment by Danik2343** [comment]
Thanks, this Best newer GUI!
