### ISSUE TITLE
qemu-system-i386.exe: invalid datetime format

### ISSUE THREAD

**Issue by yotoprules** [Tech-FZ/EmuGUI#52]
Hi,
I am pretty sure I set all the settings correctly.
When I try to start my VM, it says "invalid datetime format" even if I leave it default, or if I set it to current time.
I am using Windows 10 as my host with Qemu 20221230.

Thanks

**Comment by Tech-FZ** [comment]
So you seem to have used QEMU i386. I need to know your PC specifications and your VM configurations and how you got the error. Maybe I can try to reproduce and fix it.

**Comment by Tech-FZ** [comment]
Ah, and which version of EmuGUI did you use?

**Comment by Tech-FZ** [comment]
Update: I set up an i386 VM with EmuGUI 0.8.0.5206 and QEMU 7.2 on Windows 10 and didn't face this issue with setting the date & time to the host. Maybe it helps updating both of them to the latest stable release and try again.

**Comment by Tech-FZ** [comment]
I think we can put this aside.
