### ISSUE TITLE
Can`t excute EmuGUI

### ISSUE THREAD

**Issue by backryun** [Tech-FZ/EmuGUI#56]
C:\Users\Administrator\Desktop\EmuGUI_v1.0.2.5312_Win_amd64>emugui.exe
The SQLite module encountered an error: unable to open database file. Trying to create the file.
EmuGUI wasn't able to create the file.
The SQLite module encountered an error: unable to open database file.
['windowsvista', 'Windows', 'Fusion']
windowsvista
Windows
Fusion
Traceback (most recent call last):
  File "emugui.py", line 2048, in <module>
    win = Window()
  File "emugui.py", line 89, in __init__
    self.prepareDatabase(self.connection)
  File "emugui.py", line 546, in prepareDatabase
    cursor = connection.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
[22312] Failed to execute script 'emugui' due to unhandled exception!

This error makes can`t excute your program, how to solve it?
I already installed Qemu 8.0/Python 3.11.3.

**Comment by Tech-FZ** [comment]
Try `pip install pysqlite3`.

**Comment by Tech-FZ** [comment]
And use the included binaries which should include everything EmuGUI needs.

**Comment by Tech-FZ** [comment]
I could get EmuGUI running on both a PC I normally only use for gaming or printing and a VM where EmuGUI wasn't run before. Please check if there are problems with your binaries.
