### ISSUE TITLE
Add Existing Virtual Hard Drive

### ISSUE THREAD

**Issue by r9guy** [Tech-FZ/EmuGUI#65]
The option "Add Existing virtual Hard Drive" doesn't work, as it's opening the FileSave dialog to select a file.
It should be File Open dialog.
![image](https://github.com/Tech-FZ/EmuGUI/assets/9428627/1c5515ce-520b-448f-9218-cb2a8f72448d)

**Comment by Tech-FZ** [comment]
I was too lazy to do it. Don't worry, nothing is overwritten.

**Comment by Tech-FZ** [comment]
I forgot to close that issue...
