### ISSUE TITLE
Error while loading shared library libz.so.1

### ISSUE THREAD

**Issue by RafaelLinux** [Tech-FZ/EmuGUI#67]
Downloaded and installed in openSUSE Tumbleweed. When I launch `emugui` executable, it throws:
./emugui: error while loading shared libraries: `libz.so.1`: failed to map segment from shared object

**Comment by Tech-FZ** [comment]
Can you please give me more detail? Which Linux kernel did you use? Which desktop environment?

**Comment by Tech-FZ** [comment]
![vmplayer_8ZMvbshHGg](https://github.com/Tech-FZ/EmuGUI/assets/86562548/9118a9f8-3653-490e-8ecc-f53f686cd593)
I let you know I'm currently hunting down the issue, but so far, nothing to see. Are you sure you downloaded the right binaries?

**Comment by RafaelLinux** [comment]
> Can you please give me more detail? Which Linux kernel did you use? Which desktop environment?

I'm sorry, I toght it will was easy to identify library issue and did not include more information:

This is the link I downloaded `EmuGUI_v1.1.4.5412_Linux_amd64.tar.gz `.

Operating System: openSUSE Tumbleweed 20230818
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.9-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

**Comment by Tech-FZ** [comment]
Try to update the operating system.

**Comment by RafaelLinux** [comment]
Hello

openSUSE Tumbleweed is what is know as "rolling release", that is, is upgraded each about each week, so it's a really updated version!!!!

**Comment by Tech-FZ** [comment]
Maybe try to install the "LinuxLegacy" version and see if it helps?

**Comment by Tech-FZ** [comment]
Maybe try to copy the file in question to the EmuGUI folder?

**Comment by RafaelLinux** [comment]
Don't worry. I'll close issue.

Thank you
