### ISSUE TITLE
Add docs for Debian/Arch packages

### ISSUE THREAD

**Issue by Tech-FZ** [Tech-FZ/EmuGUI#78]
It is most suitable for the wiki, but as you may know, Linux binaries are now also available in the form of Debian and Arch packages. It should be documented how to install and use them. @user0-tb (for Debian) and @pi17763 (for Arch) are the creators of the packages, so they are most likely to know how to do it.

**Comment by pi17763** [comment]
I know it.

**Comment by pi17763** [comment]
For Arch and its descendants, download file and do `pacman -U <emugui_file>.tar.zst`.

**Comment by pi17763** [comment]
For Debian you can use `sudo apt install ./<emugui_package>.deb`.

**Comment by user0-tb** [comment]
yep

**Comment by user0-tb** [comment]
wait

**Comment by user0-tb** [comment]
you got access to your github account?

**Comment by user0-tb** [comment]
Anyways, I'll put that in the docs. Thanks.

**Comment by pi17763** [comment]
> you got access to your github account?

yes this account

**Comment by user0-07161** [comment]
https://github.com/Tech-FZ/EmuGUI/wiki/Installation-on-Arch-Linux-Debian
