### ISSUE TITLE
allow it compile through msys2/mingw

### ISSUE THREAD

**Issue by Kreijstal** [Tech-FZ/EmuGUI#86]
so that MSVC installation is not necessary, since it compiles under linux it should be possible, right?

**Comment by Tech-FZ** [comment]
Python utilises MSVC for compiling Windows binaries. This is outside of my control. Please suggest this change to the developers of Python.

**Comment by Kreijstal** [comment]
> Python utilises MSVC for compiling Windows binaries. This is outside of my control. Please suggest this change to the developers of Python.

huh, you can use python for mingw? You mean gyp?

**Comment by Tech-FZ** [comment]
> huh, you can use python for mingw? You mean gyp? You can use mingw's python to compile mingw's programs

I'm too lazy. Unless there is a reason to do what you suggested, I won't. **There is no need for switching to MinGW Python!** If you don't realise that, I may have to block you or something.
