### ISSUE TITLE
The "-machine" argument is omitted, which is required in aarch64

### ISSUE THREAD

**Issue by AurusHuang** [Tech-FZ/EmuGUI#92]
When creating ARM64 VMs, "-machine" argument is required by QEMU, with no default. This is omitted in EmuGUI, which means I'm unable to launch an aarch64 VM. 
I also suggest the default option for this argument "virt" in EmuGUI.

**Comment by Tech-FZ** [comment]
EmuGUI is using `-M` to select machines as far as I know. However, I will investigate the issue and tell you more.

**Comment by Tech-FZ** [comment]
I just tested this and there is indeed a need for this. Please specifically set your machine (NOT "Let QEMU decide") at this time. However, I can make an update which fixes the issue.

**Comment by Tech-FZ** [comment]
Please test this release: https://github.com/Tech-FZ/EmuGUI/releases/tag/v2.0.9.5620

It should fix the issue you have described.
